CREATE TYPE "public"."legal_form" AS ENUM('sole_trader', 'eK', 'GbR', 'GmbH', 'UG', 'AG', 'GmbH_Co_KG', 'OHG', 'KG', 'other');--> statement-breakpoint
CREATE TABLE "quote_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"logo_url" text,
	"slogan" text DEFAULT '' NOT NULL,
	"company_name" text DEFAULT '' NOT NULL,
	"legal_form" "legal_form" DEFAULT 'GmbH' NOT NULL,
	"street" text DEFAULT '' NOT NULL,
	"postal_code" text DEFAULT '' NOT NULL,
	"city" text DEFAULT '' NOT NULL,
	"country" text DEFAULT 'Germany' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"fax" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"website" text DEFAULT '' NOT NULL,
	"sender_place" text DEFAULT '' NOT NULL,
	"locale" text DEFAULT 'en-US' NOT NULL,
	"currency" text DEFAULT 'EUR' NOT NULL,
	"vat_rate" numeric DEFAULT '19' NOT NULL,
	"reduced_vat_rate" numeric DEFAULT '7' NOT NULL,
	"small_business" boolean DEFAULT false NOT NULL,
	"subject_template" text DEFAULT 'Quote No. {quoteNo}' NOT NULL,
	"intro_text" text DEFAULT '' NOT NULL,
	"closing_text" text DEFAULT 'Kind regards' NOT NULL,
	"validity_days" integer DEFAULT 30 NOT NULL,
	"delivery_terms" text DEFAULT 'ex works' NOT NULL,
	"payment_terms" text DEFAULT 'Net 14 days.' NOT NULL,
	"terms_text" text DEFAULT '' NOT NULL,
	"contacts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"managing_directors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"register_court" text DEFAULT '' NOT NULL,
	"register_number" text DEFAULT '' NOT NULL,
	"jurisdiction" text DEFAULT '' NOT NULL,
	"tax_number" text DEFAULT '' NOT NULL,
	"vat_id" text DEFAULT '' NOT NULL,
	"bank_accounts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"footer_logos" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quote_templates_org_id_unique" UNIQUE("org_id")
);
--> statement-breakpoint
ALTER TABLE "quote_templates" ADD CONSTRAINT "quote_templates_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_quote_templates_org" ON "quote_templates" USING btree ("org_id");